PACKAGE_NAME="osoyoo-dsi-panel"
PACKAGE_VERSION="1.0"
CLEAN="make clean"

# First module: osoyoo-panel-dsi
BUILT_MODULE_NAME[0]="osoyoo-panel-dsi"
DEST_MODULE_LOCATION[0]="/kernel/drivers/gpu/drm/panel/"
AUTOINSTALL="yes"

# Second module: osoyoo-panel-regulator
BUILT_MODULE_NAME[1]="osoyoo-panel-regulator"
DEST_MODULE_LOCATION[1]="/kernel/drivers/regulator/"
AUTOINSTALL="yes"

# Build configuration
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
