#!/bin/bash
set -e

PACKAGE_NAME="osoyoo-dsi-panel"
PACKAGE_VERSION="1.0"

case "$1" in
    purge)
        # Remove device tree overlays on purge
        rm -f /boot/overlays/osoyoo-panel-dsi-7inch.dtbo
        rm -f /boot/overlays/osoyoo-panel-dsi-10inch.dtbo
        rm -f /boot/firmware/overlays/osoyoo-panel-dsi-7inch.dtbo
        rm -f /boot/firmware/overlays/osoyoo-panel-dsi-10inch.dtbo

        echo "OSOYOO DSI Panel driver has been removed."
        echo "Don't forget to remove the dtoverlay lines from your config.txt file."
        ;;
esac

#DEBHELPER#

exit 0
